version: '3.9'

services:
  aula-api:
    container_name: aula-api
    build:
      context: ./Financeiro.Aula
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - db
    networks:
      - app

  boleto-api:
    container_name: boleto-api
    build:
      context: ./Financeiro.Boleto
      dockerfile: Dockerfile
    ports:
      - "5050:5050"
    depends_on:
      - db
    networks:
      - app
  
  db:
    container_name: db
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "SqlServer2019!"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
    ports:
      - "1433:1433"
    volumes:
      - sqlvolume:/var/opt/mssql
    networks:
      - app

volumes:
  sqlvolume:

networks:
  app:
    driver: bridge
    

#sudo docker run -e "ACCEPT_EULA=Y" -e "SA_PASSWORD=Feherr00" --name sqlserver -p 1433:1433 -v /home/felipe/docker/mssql:/var/opt/mssql/data -d mcr.microsoft.com/mssql/server:2019-latest



